version: '3'

services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 50200:3000
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - HOST=0.0.0.0
      - API_HOST=0.0.0.0
      - API_PORT=3000
    command: ["npm", "run", "dev"]
    stdin_open: true
    tty: true
