version: '3'

services:
  gateway:
    container_name: yomitai_gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - 50300:80
    restart: always

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports: []
    volumes:
      - ./client:/app
    env_file: .env
    environment:
      - HOST=0.0.0.0
      - API_HOST=0.0.0.0
      - API_PORT=3000
    command: ["firebase", "serve", "--port", "3000"]
    stdin_open: true
    tty: true

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 9005:9005 # for firebase login
    volumes:
      - ./api:/app
    env_file: .env
    environment: []
    command: ["firebase", "serve", "--port", "3000", "--only", "functions"]
    stdin_open: true
    tty: true

networks:
  default:
    external:
      name: yomitai
